ZenPrivacy/zen-desktop

- frontend/src/App.css
- frontend/src/StartStopButton.tsx
- internal/app/app.go
- internal/app/eventshandler.go
- internal/proxy/proxy.go
- internal/proxy/proxy_linux.go
Added custom error message when there is no `gsettings` binary with a link to this guide - https://github.com/anfragment/zen/blob/master/docs/external/linux-proxy-conf.md
closes #108
> Custom error message when Linux DE is not supported 

- internal/logger/logger.go
- internal/logger/setuplogger_nonprod.go
- internal/logger/setuplogger_prod.go
- tasks/build/Taskfile-darwin.yml
- tasks/build/Taskfile-linux.yml
- tasks/build/Taskfile-windows.yml
Windows (when app is running as .exe) cannot write logs to both stdout and a file simultaneously. Therefore, in the production environment, logs are written only to a file, while in non-production environments, logs are written to both.
> Separate logger setup for production and non-production environments

- internal/filter/filter.go
- internal/logger/redacted_nonprod.go
- internal/logger/redacted_prod.go
- internal/proxy/proxy.go
- internal/proxy/websocket.go
- internal/scriptlet/injector.go
This PR addresses a privacy risk associated with writing logs to disk, where sensitive information about a client's traffic history could potentially be exposed to third parties - either located on the client's computer or during transmission for debugging purposes.
To mitigate this risk, the PR introduces a new `logger.Redacted` function, which enables us to easily redact sensitive data from production logs.
> Implement redaction of sensitive data in logs

- go.mod
- go.sum
The update addresses CVE-2024-45338
> Upgrade golang.org/x/net to 0.33.0

- internal/jsrule/injector.go
- internal/scriptlet/injector.go
This change prioritizes parsing and initialization of the injections compared to first-party JS. In certain cases, like YT video ads, ad-blocking performance should get improved.
> Move scriptlet/JS rule bundle injections to the top <body>

- proxy/exclusions/common.txt
Removes hosts from the `common` HTTPS exclusions list. The issues that originally caused these hosts to be added to the list are no longer replicable.
Manual testing. To replicate, comment out `common.txt` from `proxy_<platformname>.go` under `internal/proxy`.
> Remove all hosts from proxy/exclusions/common.txt

- proxy/exclusions/common.txt
It appears that we're triggering Booking's bot protection during OTP sign-ins on https://account.booking.com/otp/email-code.
During debugging, POST requests to https://account.booking.com/api/identity/authenticate/v1.0/otp/code/submit consistently fail with `error.code: ERROR_CODE__INVALID_OTP`.
Adding `account.booking.com` to the list of transparently proxied hosts seems to resolve the issue.
Manual testing by adding `account.booking.com` to *Ignored Hosts* in the settings.
> Add `account.booking.com` to the common proxy exclusions list

- internal/networkrules/rulemodifiers/thirdparty.go
Determining whether a request is "third-party" using the `Referer` header is unreliable. In the case of document requests, Referer may contain the URL of a page that **redirected** to the current page instead of the current page itself.
Additionally, the current implementation contains a bug on [this line](https://github.com/anfragment/zen/blob/e66aa0338e5aa17f74e45b1b3a7db4fe99bfc8f6/internal/networkrules/rulemodifiers/thirdparty.go#L37) (`refererHost` and `targetHost` should be swapped), leading to incorrect detection even when `Referer` has the expected value.
This PR resolves both issues by relying on [`Sec-Fetch-Site`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Sec-Fetch-Site), which is a reliable indicator of whether a request is "third-party". Unlike …
> Rewrite $third-party matching logic to rely exclusively on the Sec-Fetch-Site header

- internal/networkrules/exceptionrule/exceptionrule.go
- internal/networkrules/exceptionrule/exceptionrule_test.go
- internal/networkrules/rule/rule.go
- internal/networkrules/rulemodifiers/contenttype.go
- internal/networkrules/rulemodifiers/domain_test.go
- internal/proxy/proxy.go
This PR changes blocking strategy by respecting user initiated requests unless `$document` modifier is present in rule.
`||scriptlet-test.pages.dev` - does not block document, but blocks all requests made from that page
`||scriptlet-test.pages.dev^$document` - blocks entire document
Also exception rules should work as expected:
`@@||scriptlet-test.pages.dev` - should cancel all rules above (@anfragment let me know if I'm wrong)
Closes #249
> Do not block user initiated requests unless  modifier is present

- internal/networkrules/rulemodifiers/removeparam.go
- internal/networkrules/rulemodifiers/removeparam_test.go
From uBo documentation's ["Static filter syntax"](https://github.com/gorhill/ublock/wiki/static-filter-syntax#removeparam):
> When using a literal regular expression, it gets tested against each query parameter **name-value pair** assembled into a single string as name=value.
Currently, `$removeparam` [matches only parameter names](https://github.com/anfragment/zen/blob/102f55a61fc7c66703d689b429521a23aefc012f/internal/networkrules/rulemodifiers/removeparam.go#L79). This PR updates the implementation to match full name-value pairs as per the documented behavior.
For compatibility with AdGuard, the modifier now also allows regular expressions to be prefixed with `~`. Such modifiers remove name-value pairs that **do not** match the regex.
New tests for `$removeparam`'s `ModifyReq` function.
> $removeparam fixes and improvements

- internal/cfg/config.go
Fixes a bug where adding custom filter lists with duplicate URLs caused issues with enabling/disabling or removing them, by adding checks for duplicates.
Manual testing.
Closes #149
> Fix duplicate URL handling when adding filter list

- internal/selfupdate/selfupdate.go
The change itself is self-explanatory. This lays the groundwork for https://github.com/anfragment/zen/pull/286 - the application should first be configured to fetch updates from the new subdomain. Only after that should the CI start uploading manifests to the new location.
> Set self-update manifests URL to update-manifests.zenprivacy.net

- internal/cfg/default-config.json
- internal/cfg/migrations.go
This PR updates outdated filter list URL for the Hungarian filter list to https://filters.hufilter.hu/hufilter-adguard.txt.
Verified that the application runs without errors after the update.
Closes #296
> fix: update Hungarian filter list URL in default config

- internal/ruletree/node.go
- internal/ruletree/ruletree.go
Fixes a phantom bug triggered in the rare case where `node.data` gets updated concurrently by multiple writers. Clarifies some related documentation.
> Add mutex to protect node.data

- internal/filter/filter.go
- internal/hostmatch/hostmatcher.go
- internal/scriptlet/addrule.go
- Fixes scriptlet exceptions by including exception syntax in the top-level matching regex.
- Optimizes hostmatcher.Get.
Existing unit tests, manual testing.
resolves #323
> Fix scriptlet exceptions

- .github/workflows/build.yml
- .github/workflows/release-manifest.yml
- .github/workflows/test.yml
- Improves the `build` CI workflow:
- Streamlines the workflow by utilizing separate jobs per platform and a unified job for attestation and release publishing.
- Adds [artifact attestations](https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds#about-artifact-attestations).
- Pins third-party action versions to commit hashes for [improved security](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions).
- Adds minimal permissions (`contents: read, checks: write`) to `release-manifest` and `test` workflows.
- Manually verified attestations: https://docs.github.com/en/actions/security-for-github-actions/u …
> Add artifact attestation generation; pin action versions in build CI workflow

- .github/workflows/build.yml
- tasks/build/Taskfile-darwin.yml
Adds macOS `.app` version with self-updates disabled.
CI runs.
Sets the ground up for #81.
> Include noselfupdate macOS production build in build CI workflow

- internal/sysproxy/exclusions/common.txt
- internal/sysproxy/exclusions/darwin.txt
- Adds `sys.redsys.es`, a Spanish payment provider website, and Stripe's `m.stripe.network` to the common proxy exclusions list
- Adds Apple Pay related hosts to the macOS exclusions list
Manual testing
> Add payment-related hosts to exclusions lists

- internal/sysproxy/exclusions/common.txt
added Openai's list of urls
It adds openAI's list of domains to the default list of Ignored hosts. got them from here:
https://help.openai.com/en/articles/9247338-network-recommendations-for-chatgpt-errors-on-web-and-apps
tested them in ignored hosts on the app.
> Added OpenAI domains to default ignored hosts

- internal/scriptlet/injector.go
Fixes CSP header injection behavior when `'unsafe-inline'` directive is already present.
From https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Content-Security-Policy#nonce-nonce_value:
> If a directive contains a nonce and unsafe-inline, then the browser ignores unsafe-inline.
Manual testing.
> Add handling for 'unsafe-inline' in CSP header processing

- frontend/src/FilterLists/index.tsx
This PR removes the `disabled` property from the `copy` and `goTo` buttons.  
As a result, these buttons are now always interactive, regardless of previous conditional states that may have blocked user actions.
- Manual testing.
Closes #417
> delete disabled from copy and goTo buttons

- internal/scriptlet/arglist.go
- internal/scriptlet/arglist_test.go
- internal/scriptlet/argsplit.go
- internal/scriptlet/argsplit_test.go
As described in #399, current scriptlet argument splitting logic is error-prone. This PR introduces a state-machine-based parser that robustly handles commas inside quoted strings.
New and existing unit tests.
closes #399
> Implement robust logic for scriptlet argument splitting

- internal/autostart/autostart_darwin.go
- internal/cfg/migrations.go
The PR fixes the issue where the proxy failed to start up on autostart on macOS.
The issue was with the `ProgramArguments` key in launchd daemon. This key defines the argument array passed to the program. Previously, the array contained only a single element, `--start`, at position 0. In Go, these values become `os.Args`, but the flag package ignores the zeroth element (https://go.dev/src/flag/flag.go#L1188), causing the `--start` flag to be missed.
By adding the program path as the zeroth element, where it belongs, we ensure the flag parser receives `--start` as the first real argument, allowing the app to start the proxy correctly on autostart.
See more on this here:
https://apple.stackexchange.com/questions/110644/getting-launchd-to-read-program-arguments-correctly
Manual testing.
> Fix proxy startup on autostart on macOS

- internal/cosmetic/injector.go
- internal/cosmetic/injector_test.go
- internal/cssrule/injector.go
- internal/cssrule/injector_test.go
Refactors `cosmetic` and `cssrule` injectors to:
1. Perform CSP modification via `csp.PatchHeaders`
2. Use `html/template`-based injections 
- New unit tests covering CSP injection
- Manual testing
closes #451
> Refactor CSS injectors to patch CSP headers and use html/template

- internal/filter/filter.go
- internal/networkrules/networkrules.go
- internal/ruletree/node.go
- internal/ruletree/ruletree.go
- internal/ruletree/slices.go
```
Optimize ruletree node memory usage
Reduce nodeKey struct size from 16 to 8 bytes by using a single type for kind
and tokenID. This saves memory and improves cache locality. I am making an
assumption that we will not have more than 2^4=16 kinds of nodes and not more than
2^28=268435456 unique tokens.
```
---
```
Use single mutex to protect node data and children
Each node in ruletree have two RWMutex structures that is 48 bytes per node.
This change uses a single Mutex to protect both children and data
structures which uses only 8 bytes of memory. This is a trade-off
between concurrency and memory usage, but in practice the contention
is low and the memory savings are significant.
```
---
```
Compact rule tree nodes to save memory
Once filter is done loading rules, we can compact the …
```
> Optimize ruletree node memory usage

- .github/workflows/build.yml
`windows-latest` was [recently switched to `windows-2025`](https://github.com/actions/runner-images/issues/12677), which quite unfortunately [doesn't come with NSIS pre-installed](https://github.com/actions/runner-images/issues/11754). This [breaks our Windows build pipelines](https://github.com/ZenPrivacy/zen-desktop/actions/runs/18065693022/job/51408056302).
We can obviously install NSIS manually in various ways, but for now just pinning the version to `windows-2022` (which should be supported for 3 more years) seems to be the simplest solution.
CI runs.
> Pin Windows build runner to windows-2022
