filter/filter.go, filter/filter_test.go, filter/response.go, filter/ruletree/node.go, filter/ruletree/rule/domain.go, filter/ruletree/rule/method.go, filter/ruletree/rule/removeparam.go, filter/ruletree/rule/rule.go, filter/ruletree/ruletree.go, frontend/src/RequestLog/index.css, frontend/src/RequestLog/index.tsx, proxy/proxy.go
=> removeparam modifiers

proxy/proxy_darwin.go
=> fix: make network service detection more reliable

internal/systray/systray_internal_windows.go, internal/systray/systray_windows.go
=> Win systray fix

docs/internal/filter-lists.md, frontend/src/FilterLists/CreateFilterList/index.css, frontend/src/FilterLists/CreateFilterList/index.tsx, frontend/src/FilterLists/index.css, frontend/src/FilterLists/index.tsx, frontend/wailsjs/go/models.ts, internal/cfg/config.go, internal/cfg/default-config.json, internal/cfg/migrations.go, internal/filter/filter.go, internal/scriptlet/addrule.go, internal/scriptlet/scriptlet_internal_test.go, internal/scriptlet/scriptlet_test.go
=> Trusted filter lists

internal/htmlrewrite/htmlrewrite.go, internal/htmlrewrite/rawbody.go, internal/scriptlet/injector.go
=> Fix "scriptlets injector misplaces script tags"

internal/app/app.go, internal/cssrule/injector.go, internal/filter/filter.go
=> Inject css rules into html document

internal/htmlrewrite/rawbody.go
It turns out the Go stdlib already provides a ready-made solution for decoding HTTP responses to UTF-8 in the form of `charset.NewReader`. It comprehensively checks both the charset in the Content-Type header and attempts to infer the encoding from the appropriate charset or http-equiv/content-type `<meta>` tags.
resolves #205
=> Simplify character encoding handling in raw body reader

.github/workflows/build.yml, scripts/build/upload-manifest.js, scripts/src/upload-manifest.ts
Introduces ARM64 builds for Linux.
resolves #226
=> ARM64 builds for Linux

COPYING.md, LICENSE, build/windows/installer/resources/eula.txt, frontend/src/SettingsManager/index.tsx, main.go, wails.json
Sets 2025 in copyright documents.
Visually.
=> Update copyright year

frontend/src/SettingsManager/UpdatePolicyRadioGroup/index.tsx, frontend/src/SettingsManager/index.tsx, frontend/wailsjs/go/app/App.d.ts, frontend/wailsjs/go/app/App.js, frontend/wailsjs/go/cfg/Config.d.ts, frontend/wailsjs/go/cfg/Config.js, frontend/wailsjs/go/models.ts, internal/app/app.go, internal/cfg/config.go, internal/cfg/default-config.json, internal/cfg/migrations.go, internal/selfupdate/executable.go, internal/selfupdate/selfupdate.go, main.go, tasks/build/Taskfile-linux.yml, tasks/build/Taskfile-windows.yml
Allows user to select update policy and perform self-update based on that.
Manual testing on MacOS.
Closes #256
=> Self-update policies

docs/external/how-to-rules.md
Improves the "How to Write Rules" public documentation by improving organization, adding a note on whitelisting domains, and adding a description to the "See Also" section.
#265
=> Update how-to rules with FAQ section and whitelisting instructions

CONTRIBUTING.md, README.md, docs/internal/localization-guide.md
1. Adds a localization guide to the project.
2. Updates the contribution guidelines and README with references to localization.
Yes.
=> Localization guide

.github/workflows/lint.yml, .golangci.yml, internal/cosmetic/sanitizer.go, internal/scriptlet/arglist.go
=> Upgrade golangci-lint to v2

frontend/i18next-parser.config.js, frontend/src/SettingsManager/LocaleSelector/index.tsx, frontend/src/SettingsManager/UninstallCADialog/index.tsx, frontend/src/i18n/index.ts, frontend/src/i18n/locales/de-DE.json
=>  Add German language support

docs/internal/testing-checklist.md
Introduce basic manual testing checklist.
Manual testing :0
=> Testing checklist

internal/sysproxy/exclusions/common.txt
=> Fix hostname entry for LastPass and add FreedomPay to exclusions list

internal/httprewrite/httprewrite.go, internal/httprewrite/rawbody.go
=> Allow httprewrite.BufferRewrite to return an error

internal/networkrules/rulemodifiers/domain.go, internal/networkrules/rulemodifiers/domain_test.go
Self-explanatory
Unit and manual testing
#305
=> Dont match request if URL is matching inverted domain

internal/cfg/default-config.json, internal/cfg/migrations.go
Self-explanatory.
I didn't. Sorry.
=> Add minor changes related to the "Zen - Ads" filter list

README.md, SECURITY.md, docs/internal/security-architecture.md
=> Add a security policy and documentation on security architecture

CHANGELOG.md
=> Update CHANGELOG for v0.10.0 release

PRIVACY_POLICY.md
Adds a privacy policy.
I never verify that my code works. Why would I do that?
=> Add PRIVACY_POLICY.md

README.md
=> Add Homebrew installation instructions to README.md

wails.json
=> Update product version to 0.10.1 in wails.json

CHANGELOG.md
=> Update the changelog with v0.10.1 release notes

wails.json
=> Set productVersion to 0.11.0 in wails.json

frontend/src/SettingsManager/LocaleSelector/index.tsx, frontend/src/i18n/index.ts, frontend/src/i18n/locales/zh-CN.json
This PR adds Chinese language support to Zen Privacy as requested in #167
- I followed the steps in the localization guide
- I verified manually that the labels from the translation file are picked up when switching in the settings
Closes #167
=> I18n adding chinese lang support

internal/sysproxy/exclusions/common.txt
=> Add signpath.io to the list of common proxy exclusions (digital infra)

internal/scriptlet/addrule.go, internal/scriptlet/arglist.go, internal/scriptlet/arglist_test.go, internal/scriptlet/injector_internal_test.go
Adds `trusted-` scriptlet handling to the scriptlets injector.
New and existing automated tests.
=> Implement trusted rule handling in scriptlets injector

internal/autostart/autostart_linux.go, internal/autostart/autostart_windows.go, internal/certgen/get.go, internal/certstore/diskcertstore.go, internal/cfg/systemdirs_darwin.go, internal/cfg/systemdirs_linux.go, internal/cfg/systemdirs_windows.go, internal/constants/constants.go, internal/constants/instanceid_nonprod.go, internal/constants/instanceid_prod.go, internal/filter/filterliststore/diskcache/cache.go, internal/logger/logger.go, internal/logger/setuplogger_nonprod.go, internal/logger/setuplogger_prod.go, internal/selfupdate/executable.go, internal/selfupdate/selfupdate.go, main.go
=> Refactor to centralize app name and other constants in a new `constants` package

.github/workflows/build.yml
Introduces Windows artifact signing via SignPath.
Manual testing with CI runs.
=> SignPath binary signing

internal/sysproxy/exclusions/common.txt
=> Add payu.com to the list of common proxy exclusions

internal/sysproxy/exclusions/common.txt
=> Add updates.ghub.logitechg.com to the list of common proxy exclusions

wails.json
=> Bump product version to 0.11.2 in wails.json

.github/FUNDING.yml
=> Add Patreon username to GitHub sponsorship options

frontend/i18next-parser.config.js, frontend/src/SettingsManager/LocaleSelector/index.tsx, frontend/src/i18n/index.ts, frontend/src/i18n/locales/it-IT.json
Adds an Italian translation to Zen-Desktop, localizing UI text and messages for Italian-speaking users. No changes to functionality—only text updates.
- Manually reviewed all modified files for correct translation and formatting.
- Tested the application locally to ensure Italian text displays correctly throughout the UI.
- Improves accessibility for Italian users.
- No linked GitHub issue; this is a localization enhancement.
=> Italian localization for Zen-Desktop

README.md
=> Add Winget installation instructions to README
